### ISSUE TITLE
Base layer scanner should read current ConsensusConstants from the base node, according to the version in the blockheader

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari-dan#115]
Specificallly, we need:

- VnConfirmationTime (To be applied to base layer scanning)
- `validator_node_timeout` (To be used to know when to reregister)

**Comment by brianp** [comment]
`validator_node_timeout` is used in the [base_layer_epoch_manager](
https://github.com/tari-project/tari-dan/blob/development/applications/tari_validator_node/src/p2p/services/epoch_manager/base_layer_epoch_manager.rs#L176) and should be `expiry_in_blocks / epoch_duration - 1` so a VN will register _before_ the expiration occurs.
