### ISSUE TITLE
Template Developer tool - initial

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari-dan#1189]
## Problem Background

Currently, template development is not a smooth process, especially for new developers. We want to simplify the process as much as possible. 

This tool should feel familiar to rust developers.

## Initial version

The feature set for the initial version of this tool is kept minimal so that we can get feedback before committing a lot of development time. Specifically:
 
- Setup the boilerplate files for a new template project
- Setup the boilerplate for a new template
- Deploy a template to various networks (mainnet, testnet, local/swarm)

The binary should be named `tari`

### `tari` command

- Output should be clear and "friendly". Make use of emojis 🥇 
- We can ask questions requiring input from the user if needed, but these should be skipped if provided as a cli arg to allow for scripting
- Commonly used arguments/cli flags should have a single character alias
- Users should be free to choose how they want to structure their project e.g. where they want to put each template. We can however expect the `tari.config.toml` to be in the cargo/git root.

**Arguments**
- `--config` , `-c` - path to the config (Default to git/cargo root + `tari.config.toml`)

### `tari create my_project`

Sets up a new project with the following structure under the new directory `my_project/` (if empty):

- `.git` - command sets up git i.e. runs `git init` 
- `tari.config.toml` - adds a boilerplate config file for `tari`
- `.gitignore` - Typical rust ignore file, `target/` etc
- `README.md` - boilerplate readme
- `Cargo.toml` - workspace Cargo.toml with no members

Optional arguments

`--template`, `-t`: arg `{name}`creates a new template named `{name}` This is the same as using `tari new` after `tari create`
There may be other arguments based on what is in the `tari.config.toml`

### `tari new my_template`

Creates a new WASM template in the current working directory.

**Arguments**

- `--output`, `-o` - the path to output the new template. This will create any subfolders that do not exist if necessary e.g. `--path templates/my_template`
- `--template {name}` - we'll have several pre-defined templates as well as allowing custom ones e.g. `--template counter`, `--template my_tari_template`. Custom templates can be added to `tari.config.toml` (Default hello_world or blank)

### `tari deploy [my_template]`

Deploys the given template crate (found in the root Cargo.toml workspace), or the template at the given path, or the template in the current working directory. The user should confirm that they want to do continue, as this will cost fees (`--yes`, `-y` flag can skip the confirmation)

**Arguments**

- `--network [mainnet, testnet, my_network]`, `-n` - the target network. Custom networks can be added in tari.config.toml. Defaults to the configured default_network in the config. 

How do we serve the templates?

This is currently difficult to answer. We may change how this works in future but currently, we require a web URL. For now, perhaps we can stage and push the template binary to github and retrieve the github URL. This will require git staging to be clean i.e. no already staged files. Open to suggestions. 

## Similar tools in other networks (Thanks @mrnaveira )

Ethereum
There are two main frameworks:
Hardhat (JS based)
https://hardhat.org/tutorial/deploying-to-a-live-network
https://github.com/NomicFoundation/hardhat-boilerplate
Uses envvars for keys
Has a config file for networks (urls, accounts,...), paths, solidity version, etc.
Deployment is done using “ignition” modules
Foundry (Rust based)
https://github.com/foundry-rs/foundry
https://book.getfoundry.sh/getting-started/installation
https://github.com/foundry-rs/foundry/tree/master/crates/config
It has a toml config file similar to hardhat
Deployments are done via CLI or custom Solidity scripts

Solana
https://solana.com/docs/intro/dev
https://solana.com/docs/programs/deploying

It has a single CLI command solana, that is used for everything:
Deployment of contracts
Managing keys and accounts
Config management
Starting local networks

Radix
https://docs.radixdlt.com/v1/docs/getting-rust-scrypto
https://docs.radixdlt.com/docs/scrypto-cli-tool
It has a convoluted installation process
Fragmented CLI tools: testing, deploying, etc.

**Comment by ksrichard** [comment]
PR: https://github.com/tari-project/tari-cli/pull/5

**Comment by sdbondi** [comment]
Done
