### ISSUE TITLE
[web-ui] build failures without npm

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari-dan#121]
Currently we build the web-ui in the build.rs, and this requires npm to be setup in the environment.
This means that a node environment is required to be setup to build the vn which can be annoying when running the VN from a different shell (like intelij run) leading to confusing build failures.

I suggest rather that we have to manually run npm to build the web-ui to be included in the binary.
There are a few options from here:
1. Let that be that, if you dont build the webui, it will display a blank page/help page.
2. add an optional cli flag `--webui-root ./whatever` that overrides the content served on the web-ui port.
3. stringhandler: Only run npm if a certain env is set / nodejs is setup
4. Cifko: ignore the error in the build.rs and emit a [build warning](https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargo-warning)

no 1. is simpler, ~~we'll have to allow CORS in development because you may want to dev on the web-ui using `npm serve`~~
no 2. allows the updated content to be served directly from the VN, making dev easier. But you can serve from a node server anyway so YAGNI

Both are fine for me, but 2 is a feature that needs to be added that may/may not be generally useful.

For production builds, we add the npm build to the process (build script or whatever).

**Comment by CjS77** [comment]
Yeah, push it up to a `build.sh` that does all the steps including `cargo build`
