### ISSUE TITLE
Send the Payload as part of the first proposal

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari-dan#125]
Currently, all proposals only use the PayloadId. The payload is distributed via the NewView messages. The problem is that a VN may receive a proposal, but have not yet received the payload via mempool. NewView messages are only sent to the leader of the round, so it would not have received it that way either. 

One way to solve this is to send another message to the nodes, but maybe a good solution is to just include the full payload in the first proposal (i.e. when PayloadHeight = 0)

**Comment by sdbondi** [comment]
Done
