### ISSUE TITLE
Implement VoteMessage signing with actual signature

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari-dan#127]
In `hotstuff_waiter` `on_receive_proposal`, the vote message is created and signed here:

```rust 
  let mut vote_msg = VoteMessage::new(*local_node.hash(), local_shard, decision, votes.clone());
                        vote_msg.sign();
```

However, `vote_msg.sign` is just a stub right now:

```rust
 pub fn sign(&mut self) {
        // TODO: better signature
        self.signature = Some(ValidatorSignature::from_bytes(&[9u8; 32]).unwrap())
    }

```

This should be implemented and tested.

**Comment by Cifko** [comment]
@mrnaveira did it, but the `all_shard_nodes` should be part of the signature as well. But that is waiting for the `Borsh` tickets.

**Comment by sdbondi** [comment]
Done
