### ISSUE TITLE
Leader should only send a proposal once it has received n - f NewView messages

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari-dan#137]
Currently, the leader will send a proposal as soon as it receives the first NewView message. Doing this is risky because it may send out a proposal that is based on a lower `justify` height than the majority of VNs has. If this is the case, the other VNs will not vote for it and it will fail consensus. 

What it should do is store each high_qc received from the NewView messages and only send once it has received n - f

**Comment by sdbondi** [comment]
Closed in #183
