### ISSUE TITLE
[Hotstuff] Before Voting on the first round, the VN should run the wasm and sign the resulting new substate that will be stored in its shard

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari-dan#148]
Once a VN has received all proposals from all leaders, it should have all the data necessary to run the WASM and get the result. 

The result for the data that will be stored in the shard must be signed as part of the VoteMessage. The QC must also be altered to have a proof that the signed state is correct and that all nodes in the QC have signed the resulting data.

Upon receiving a proposal, a new step must be added that checks:
For each shard, the QC for the resulting data is valid

**Comment by stringhandler** [comment]
If it fails, the node should vote with `QuorumDecision::Reject`

**Comment by sdbondi** [comment]
Closing this as this is done by the JMT
