### ISSUE TITLE
[VNUI] Only show one row per recent transaction

### ISSUE THREAD

**Issue by Cifko** [tari-project/tari-dan#203]
The rows for recent transactions should show:

| Time | Payload Id | Component | Function | Shard | Max Height | Votes at Current Height |
| <Time submitted> | <Payload Id> | <Component or Null for functions> | <Function name from json> | Shard | Max(PayloadHeight) | <Votes for current height> |

Clicking on a row should take you to the payload details page which shows:
1. All the HS nodes
2. All the HS votes
3. The full Payload Json
4. Any substates pledged and created (from the substates table)

**Comment by sdbondi** [comment]
This is done
