### ISSUE TITLE
Add RejectReason to QuorumCertificate

### ISSUE THREAD

**Issue by mrnaveira** [tari-project/tari-dan#207]
Currently only a decision Accept or Reject is attached to a QC. I suggest adding a strict enum:

```rust 
enum RejectReason {
   ShardsNotPledged(Vec<ShardId>),
   ExecutionFailure
}
```

I think that strings should be avoided here, since this must form part of the QC's challenge and the challenges must agree.

**Comment by sdbondi** [comment]
Done
