### ISSUE TITLE
[consensus] Local leader should change according to view

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari-dan#222]
A different local leader should be selected in subsequent hotstuff views.

A naive but simple approach:
`view% |committee|`

Acceptance criteria: 
-  subsequent view for a given committee of size > 1 result in different leaders
- add a test that checks this

Ideally, the leader should be unpredictable for external observers to prevent leader DoSing. However, I think this requires a VRF, which will require more digging, so the view-mod-committee-size approach is fine for now. Other suggestions welcome.

https://medium.com/codechain/tenderand-randomized-leader-election-in-tendermint-a3663d863479

**Comment by stringhandler** [comment]
Kinda related to #221

**Comment by CjS77** [comment]
Are you sure you mean round?

Each HotStuff transaction proceeds via 4 rounds, PRE_COMMIT, COMMIT, .. etc. The leader can't change for these rounds.

**Comment by stringhandler** [comment]
The original issue was created by @sdbondi  on Github projects, I just converted it to an issue. I'll reword it. We've used `round` in the code to represent `view` so that needs updating as well

**Comment by CjS77** [comment]
I suspected as much, but wanted to be certain :+1:

**Comment by sdbondi** [comment]
Closed by #221

**Comment by sdbondi** [comment]
Reopening because there's still more to do on this (leader timeouts etc)

**Comment by sdbondi** [comment]
Second thoughts added a new issue here: #251
