### ISSUE TITLE
If EpochManagerService errors, it should shut down the whole vn

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari-dan#343]
Currently if the EpochManagerService fails, the node continues to run, and all requests to EpochManagerHandle return `Epoch manager error: Could not send to channel`.

This can be reproduced by adding this line to the EpochManagerService:

```
   pub async fn run(&mut self, mut shutdown: ShutdownSignal) -> Result<(), EpochManagerError> {
        // first, load initial state
        self.inner.load_initial_state().await?;

// -------------------
      // RETURN ERR
      return Err(.....make an error....);

// -------------


        loop {
            tokio::select! {
                Some(req) = self.rx_request.recv() => self.handle_request(req).await,
                _ = shutdown.wait() => {
                    dbg!("Shutting down epoch manager");
                    break;
                }
            }
        }
        Ok(())
    }
```

My suggestion to fix this is to store the JoinHandle to the EpochManagerService (it's currently discarded in `applications/tari_validator_node/src/p2p/services/epoch_manager/initializer.rs`) and join it in DanNode (applications/tari_validator_node/src/dan_node.rs)

**Comment by sdbondi** [comment]
Fixed in #366
