### ISSUE TITLE
[code-template] Make a code template provider interface

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari-dan#65]
get_code_template(template_id) -> WasmModule
Blocked by "[code-template-service] Download the template binary from the URL"

template_id will likely be the UTXO hash/commmitment but could be any info that is uniquely identifiable and indexable from the public blockchain. A wallet will have to provide the ID when building a transaction involving a template.

Acceptance criteria:
1. Trait that abstracts the mapping between a template hash (from an instruction) to an instance of the template code
2. Implement this trait so that the impl is able to provide templates that have been found on the base layer, downloaded and verified
3. Errors if, the template_id cannot be found and if the template does not have either `valid` or `deprecated` status
4. Load the template bytes into the WasmModule type (we may want an abstraction for "anything that can be executed" rather than a WasmModule but WasmModule is fine for now)

**Comment by sdbondi** [comment]
This was completed in #47

**Comment by jorgeantonio21** [comment]
Hey guys, it seems this issue has been addressed. I will close it, then.
