### ISSUE TITLE
[base_layer] consolidate hash domains between L1 and L2 in new crate

### ISSUE THREAD

**Issue by stringhandler** [tari-project/tari-dan#710]
Some Minotari hash domains are required in the DAN repo for interoperability with L1. This has resulted in either hash domains being copied across into the DAN code, or the entire tari_core being included just for 1 or 2 hash domains.

Propose that we create a new crate `tari_hash_domains` that contains common hash domains for L1 and L2 with minimal dependencies i.e. tari_crypto.

**Comment by stringhandler** [comment]
any more detail @sdbondi ?

**Comment by sdbondi** [comment]
@stringhandler thanks - added some context

**Comment by Cifko** [comment]
On base layer : [PR 5969](https://github.com/tari-project/tari/pull/5969)
On second layer: [PR 774](https://github.com/tari-project/tari-dan/pull/774)
