### ISSUE TITLE
[walletd] show resource names instead of resource address

### ISSUE THREAD

**Issue by Cifko** [tari-project/tari-dan#809]

**Comment by Cifko** [comment]
In current state it shows the `resource_address` when there is no `token_symbol`. Do you want to show `resource_address` all the time?

**Comment by stringhandler** [comment]
Interesting. We must then add a token_symbol for XTR so that it should this by default.

I would rather show the token_symbol, then if that doesn't exist the name, then if that doesn't exist, show the resource address

**Comment by Cifko** [comment]
Correct me if I'm wrong, but there's not such thing as a name, it's either symbol or address. The current symbol is `tXTR2`, that's why it's shown. There is a small bug in the in UI that tries to shorten whatever is printed, and when it's smaller it generates the weird string `tXTR2...tXTR2`. I'm fixing that.

**Comment by stringhandler** [comment]
Cool, that's fine
