### ISSUE TITLE
Split VNs into exact size committees

### ISSUE THREAD

**Issue by Cifko** [tari-project/tari-dan#821]

**Comment by Cifko** [comment]
The solution for this is not decided yet. We have a outstanding PR #803 that makes the committee size +-1 `committee_size`. But the committee range is not uniform now.
Another discussed ideas
- the shard key will be just order in which the VNs are assigned to the buckets. Bad think is that a lot of VNs will move from one committee to another on epoch change.
- changing the shardid of each VNs to fall into a desired bucket. This is probably not doable because during the VN registration we don't know the final number of buckets when the epoch change (many VNs can still be registered). Even if you find a way to construct the shardid somehow. And noone register in the next epoch, some VNs can be invalid in the next epoch (VN registration validity passes for them). You would have to move the existing VNs from their current committees to somewhere else to achieve balance.

**Comment by sdbondi** [comment]
This is done in #1031
