### ISSUE TITLE
Bug(state sync): if a substate already exists, the sync errors

### ISSUE THREAD

**Issue by Cifko** [tari-project/tari-dan#870]
This can happen if another state sync has already synced the substates. Perhaps we should only sync one at a time since it is likely that we'll receive duplicates and multiple simultaneous requests diminish the benefit of the state inventory pattern.

**Comment by Cifko** [comment]
Can this still happen? I see that we sync with one peer at a time. And we process everything in order block by block. This is the correct place `dan_layer\comms_rpc_state_sync\src\manager.rs:399`, right?

**Comment by sdbondi** [comment]
This cannot happen since the new sync was implemented
