### ISSUE TITLE
bug(consensus): inbound message handler future can be aborted resulting in dropped messages and blocks

### ISSUE THREAD

**Issue by sdbondi** [tari-project/tari-dan#887]
Discovered by @Cifko 

In the main select loop in the consensus worker

The `inbound_message_worker.next(..)` future performs missing transaction processing on proposals. 
If any other branch in this select loop is ready, this future is aborted. This manifests most commonly 
as blocks arriving in the logs but then no further logs appear.

In most cases, [this epoch manager call](https://github.com/tari-project/tari-dan/blob/b7ccff2084577985f5ff2c0ed53714ee9a77635a/dan_layer/consensus/src/hotstuff/on_inbound_message.rs#L164) is aborted. "Requester abandoned request" error in logs

```rust
   tokio::select! {

                msg_or_sync = self.inbound_message_worker.next(current_height) => {
                    if let Err(e) = self.on_new_hs_message(msg_or_sync).await {
                        self.on_failure("on_new_hs_message", &e).await;
                        return Err(e);
                    }
                },

                Ok(event) = epoch_manager_events.recv() => {
                    self.handle_epoch_manager_event(event).await?;
                },
// ...
}
```

**Comment by Cifko** [comment]
solved in #889
