### ISSUE TITLE
[fees] investigate why fees differ for the same transactions

### ISSUE THREAD

**Issue by Cifko** [tari-project/tari-dan#906]
Validators agree on the same fee, but they differ for stress test transactions by a few uXTR2.
This is probably because there are differences in the size of the outputs, which may be valid but still warrants investigation.

**Comment by Cifko** [comment]
data : VaultId(BorTag(Required(Hash([163, 139, 31, 151, 15, 72, 234, 94, 118, 54, 122, 136, 190, 33, 68, 242, 171, 79, 225, 98, 81, 232, 184, 173, 201, 84, 197, 153, 127, 88, 87, 21]))))

CBOR : [216, 132, 152, 32, 24, 163, 24, 139, 24, 31, 24, 151, 15, 24, 72, 24, 234, 24, 94, 24, 118, 24, 54, 24, 122, 24, 136, 24, 190, 24, 33, 24, 68, 24, 242, 24, 171, 24, 79, 24, 225, 24, 98, 24, 81, 24, 232, 24, 184, 24, 173, 24, 201, 24, 84, 24, 197, 24, 153, 24, 127, 24, 88, 24, 87, 21]

Size: 66

-------
data : VaultId(BorTag(Required(Hash([129, 17, 173, 127, 177, 111, 239, 53, 130, 57, 249, 68, 20, 35, 255, 7, 26, 168, 77, 164, 123, 95, 21, 74, 252, 245, 82, 176, 195, 222, 113, 14]))))

CBOR: [216, 132, 152, 32, 24, 129, 17, 24, 173, 24, 127, 24, 177, 24, 111, 24, 239, 24, 53, 24, 130, 24, 57, 24, 249, 24, 68, 20, 24, 35, 24, 255, 7, 24, 26, 24, 168, 24, 77, 24, 164, 24, 123, 24, 95, 21, 24, 74, 24, 252, 24, 245, 24, 82, 24, 176, 24, 195, 24, 222, 24, 113, 14]

Size: 63

**Comment by stringhandler** [comment]
What's the purpose of the 24's in between every array element? The second one has 26x24s and the first has 29x24s in the array portion (i.e. after the 163 in the first and 129 in the second)

**Comment by Cifko** [comment]
> What's the purpose of the 24's in between every array element? The second one has 26x24s and the first has 29x24s in the array portion (i.e. after the 163 in the first and 129 in the second)

Honestly I don't know why is CBOR encoding this way. You can test the CBOR encoding on [http://cbor.me](http://cbor.me) (any number >=24 will have extra byte).

#909 solved this
